### ISSUE TITLE
I think you have code trying to push the image to your Docker repo.

### ISSUE THREAD

**Issue by somenewaccountthen** [wpafbo79/ai-docker#41]
-oh i did ran that manually in the dir because reasons.. So maybe to do with that..

[Warning] One or more build-args [GIT_REPO] were not consumed
Successfully built c8ce71c6ca5b
Successfully tagged wpafbo79/cuda-with-prereqs:cuda-11.8.0_tini-0.19.0
Successfully tagged wpafbo79/cuda-with-prereqs:latest
Uploading...
The push refers to repository [docker.io/wpafbo79/cuda-with-prereqs]
7502adfe1a30: Preparing 
781ffffa5ade: Preparing 
22a11bc61346: Preparing 
2fcd5b69d61b: Preparing 
eb64737a07df: Preparing 
0006e9e9490d: Waiting 
40043f2eb50b: Waiting 
6515074984c6: Waiting 
denied: requested access to the resource is denied

I think i can just ignore it, but i just wanted you to know.

PS: How do you 'make'  i always get:  (Maybe i missing some tools?)

(base) root@linuxdesktop:~/docker/ai-docker-ET$ make
echo cuda-with-prereqs-images mini-cuda-base-images mini-cuda-with-prereqs-images real-esrgan-images gfpgan-images basujindal-stable-diffusion-images compvis-stable-diffusion-images invokeai-images
cuda-with-prereqs-images mini-cuda-base-images mini-cuda-with-prereqs-images real-esrgan-images gfpgan-images basujindal-stable-diffusion-images compvis-stable-diffusion-images invokeai-images
make -C cuda-with-prereqs/ image
make[1]: Entering directory '/home/root/docker/ai-docker-ET/cuda-with-prereqs'
./create-compose-file.sh > docker-compose.yml
./build.sh

./build.sh: 4: source: not found
./build.sh: 5: source: not found
./build.sh: 7: build: not found
make[1]: *** [Makefile:9: image] Error 127
make[1]: Leaving directory '/home/root/docker/ai-docker-ET/cuda-with-prereqs'
make: *** [Makefile:59: cuda-with-prereqs-images] Error 2

UPDATE:
Adding SHELL := /bin/bash  in Makefiles works on my system.

**Comment by wpafbo79** [comment]
Thanks for reaching out, but it is working as intended.  I have the build system specifically so it is easy to publish everything to my Docker repo.  This is still an alpha-level project as I don't have much time to dedicate to it right now.  Perhaps I should change the behavior so others can toy around with the repo without having to deal with the publish error.

As for make, what shell are you running under?  zsh?  ksh?  I'll have to update the makefiles to specify bash.
